package model

var schema = `
CREATE TABLE IF NOT EXISTS user (
	id 			SERIAL PRIMARY KEY,
	email	 	VARCHAR(30) NOT NULL,
	created_at 	TIMESTAMP WITH TIME ZONE DEFAULT NOW() 
)

CREATE TABLE IF NOT EXISTS project (
	id  		SERIAL PRIMARY KEY,
	user_id 	INTEGER REFERENCES user(id) ON DELETE CASCADE,
	name 		TEXT NOT NULL UNIQUE,
	created_at	TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TYPE request_type AS ENUM ('GET', 'POST', 'PUT');

CREATE TABLE IF NOT EXISTS route (
	id  			SERIAL PRIMARY KEY,
	project_id		INTEGER NOT NULL REFERENCES project(id) ON DELETE CASCADE,
	type 			request_type DEFAULT 'GET',
	path 			TEXT NOT NULL,
	destination 	TEXT NOT NULL,
	body			TEXT,
	created_at		TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS query (
	id 				SERIAL PRIMARY KEY,
	route_id		INTEGER REFERENCES query(id) ON DELETE CASCADE,
	NAME 			VARCHAR(20) NOT NULL,
	VALUE 			VARCHAR(50) NOT NULL
)
`
