kind: pipeline
type: docker
name: default
   
steps:
- name: deployment
  image: appleboy/drone-ssh
  script:
    - git clone https://github.com/ikeohachidi/chapi
    - docker build -t chapi ~/chapi
    - chmod +x ~/chapi/command
    - ~/chapi/command --docker-run