kind: pipeline
type: docker
name: default
   
steps:
- name: deployment
  image: appleboy/drone-ssh
  settings:
    host:  
      from_secret: host
    username: 
      from_secret: username
    password: 
      from_secret: password
    port: 22
    script:
      - git -C chapi pull || git clone https://github.com/ikeohachidi/chapi
      - cd chapi
      - source ~/.bashrc
      - chmod +x command
      - ./command --docker-run